### ISSUE TITLE
Astronomer Open Edition github

### ISSUE THREAD

**Issue by marcusrehm** [jghoman/awesome-apache-airflow#47]
Hi,

I think that the description about [Astronomer Open Edition github](https://github.com/astronomerio/astronomer) in [Airflow deployment solutions](https://github.com/jghoman/awesome-apache-airflow#airflow-deployment-solutions) section is wrong.

It's not really open, they provide it under [Astronomer Platform Enterprise Edition license.](https://github.com/astronomer/astronomer#license).

**Comment by jghoman** [comment]
Good point.  Want to do a PR to clarify the language?

**Comment by marcusrehm** [comment]
Sure @jghoman ! I'll do it.
